# Generated by Django 4.2.3 on 2023-07-30 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_blog_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 30, 15, 18, 10, 245249)),
        ),
    ]
