# Generated by Django 4.2.3 on 2023-07-30 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_blog_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(verbose_name=datetime.date(2023, 7, 30)),
        ),
    ]
